name: Build Reports for Library

on:
  push:
    tags:
      - "report-*"

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure environment
        uses: ./.github/workflows/actions/build-env-setup

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build, Test, Package
        run: mvn clean compile
        shell: bash

      - name: Using upload target
        run: echo ${GITHUB_REF_NAME:8}+$GITHUB_RUN_NUMBER
        shell: bash

      # Filter the pom files to actually have the version number in it
      - name: Update pom file
        run: find . -type f -regex ".*/pom\.xml" -exec sed -i.bak s/LOCAL-SNAPSHOT/${GITHUB_REF_NAME:8}+$GITHUB_RUN_NUMBER/ {} \;
        shell: bash

      - name: Update link template
        run: find . -type f -regex ".*/latest-release-link-template\.html" -exec sed -i.bak s/LOCAL-SNAPSHOT/${GITHUB_REF_NAME:8}+$GITHUB_RUN_NUMBER/ {} \;
        shell: bash

        # Now run the results
      - name: Run reporting
        run: mvn site -P reporting -Dgpg.skip
        shell: bash

      - name: Upload docs
        run: bash src/automate-build/sendDocsToS3.sh s3://www.erigir.com/open-source/docs/wrench/${GITHUB_REF_NAME:8}+$GITHUB_RUN_NUMBER
        shell: bash

      - name: Upload docs part 2
        run: aws s3 cp src/automate-build/latest-release-link-template.html s3://www.erigir.com/open-source/docs/wrench/index.html
        shell: bash




      - name: Save coverage reports
        uses: ./.github/workflows/actions/test-report
