name: Build and Deploy Production Library

on:
  push:
    tags:
      - "release-*"

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest
    environment: ErigirGeneral

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure environment
        uses: ./.github/workflows/actions/build-env-setup

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Dump private key to file
        run: printf '%s\n' "${{secrets.PGP_SECRET_KEY_BASE_64}}" > $HOME/pgp_secret_b64.txt
        shell: bash

      - name: Decode private key
        run: base64 -d $HOME/pgp_secret_b64.txt > $HOME/pgp_secret.asc
        shell: bash

      - name: Build, Test, Package
        run: mvn clean compile
        shell: bash

      - name: Echo build
        run: echo ${GITHUB_REF_NAME:8}+$GITHUB_RUN_NUMBER
        shell: bash

        # Filter the pom files to actually have the version number in it
      - name: Update POM
        run: find . -type f -regex ".*/pom\.xml" -exec sed -i.bak s/LOCAL-SNAPSHOT/${GITHUB_REF_NAME:8}+$GITHUB_RUN_NUMBER/ {} \;
        shell: bash

      - name: Update link template
        run: find . -type f -regex ".*/latest-release-link-template\.html" -exec sed -i.bak s/LOCAL-SNAPSHOT/${GITHUB_REF_NAME:8}+$GITHUB_RUN_NUMBER/ {} \;
        shell: bash

        # Update documentation
      - name: Build website
        run: mvn site -P reporting -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE}} -Dgpg.keyname=${{ secrets.GPG_KEYNAME}} -Dgpg.homedir=$HOME
        shell: bash

      - name: Send website to S3
        run: bash src/automate-build/sendDocsToS3.sh s3://erigir-website/open-source/docs/wrench/${GITHUB_REF_NAME:8}+$GITHUB_RUN_NUMBER
        shell: bash

      - name: Update link in S3
        run: aws s3 cp src/automate-build/latest-release-link-template.html s3://erigir-website/open-source/docs/wrench/index.html
        shell: bash

        # - aws s3 cp target/site s3://erigir-website/open-source/docs/wrench/$GITHUB_RUN_NUMBER --recursive
        # This is actually significantly easier than trying to use the maven release plugin when you wont be pushing to master,
        # and when the tagging has already happened
        # Build and upload
      - name: Publish to sonatype
        run: mvn --settings .github/build_server_maven_settings.xml -Dsonatype.username=${{secrets.SONATYPE_USERNAME}} -Dsonatype.password=${{secrets.SONATYPE_PASSWORD}} -Dpgp.secretkey=keyfile:$HOME/pgp_secret.asc -Dpgp.passphrase=literal:${{ secrets.PGP_PASSPHRASE}} -DskipTests javadoc:jar source:jar deploy
        shell: bash

      - name: cleanup
        run: rm $HOME/pgp_secret_b64.txt $HOME/pgp_secret.asc
        shell: bash

      # Will add this later once I figure out how on github-Actions
      # - mvn -s build_server_maven_settings.xml site:site
      # - git checkout gh-pages
      # - cp -R target/site/* .
      # - git add .
      # - git config --global user.email "build@erigir.com"
      # - git config --global user.name "Github Actions Build Server"
      # - git commit -a -m "Updating documentation"
      # - git push origin gh-pages

      - name: Save coverage reports
        uses: ./.github/workflows/actions/test-report
